### ISSUE TITLE
static order number

### ISSUE THREAD

**Issue by mschiele** [wirecard/prestashop-ee#208]
We are trying to use this version of the module. The order number is statically written down in the code. This should not be the case!

https://github.com/wirecard/prestashop-ee/blob/2dd25856894be1c727ec69f2789cbe402acdce8f/wirecardpaymentgateway/helper/AdditionalInformationBuilder.php#L167

**Comment by serucee** [comment]
Hi,

we will fix this is as soon as possible and inform you once the new release is available. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @mschiele ,

the issue was fixed in the latest released version https://github.com/wirecard/prestashop-ee/releases/tag/2.2.1

Best regards,
Wirecard Shop Systems Team
