### ISSUE TITLE
SmartyException with SEPA Direct Debit

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#210]
**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1.28
Wirecard Module Version: 2.2.1

### Issue

**Problem description:**

Payment by Wirecard SEPA Direct Debit ends up with a SmartyException:

<img width="1042" alt="wirecard-ee-smartyexception" src="https://user-images.githubusercontent.com/30295473/64623484-56495d00-d3e9-11e9-9f8a-f411b25b29e7.png">

Other payment methods do work

**Comment by pretzelhands** [comment]
Hi,

we will fix this is as soon as possible and inform you once the new release is available. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by fuchsbart** [comment]
@pretzelhands is there any news about the fix / update?

**Comment by tomazpu** [comment]
Hi, 

we fixed the issue, currently we are in the process of merging and testing that everything is working as expected. A release will follow in the next days. Thank you, for you penitence.

Best regards, 
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello!

We now have made a new release which addresses this issue! You can find the updated version in [our releases](https://github.com/wirecard/prestashop-ee/releases/tag/2.3.0).

Best regards,
Wirecard Shop Systems Team
