### ISSUE TITLE
UndefinedMethodException - Credit Card Payment

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#212]
### Versions

**PrestaShop version:** 1.7.5.1  
**PHP version:** 7.1.28
Module Version: 2.2.1

### Issue

Credit Card Payments don't work, orders get placed but the following error occurs.

![Bildschirmfoto 2019-09-11 um 12 39 31](https://user-images.githubusercontent.com/30295473/64690720-5ef56e00-d491-11e9-8f3c-26311cc5ced8.png)

The Credit Card Payments are configured as purchase.

**Comment by pretzelhands** [comment]
Hi,

we will fix this is as soon as possible and inform you once the new release is available. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by mschiele** [comment]
Hi,
what's the status here? We urgently need the module as we are running out of time switching our payment provider.

Best regards

**Comment by tomazpu** [comment]
Hi, 

we fixed the issue, currently we are in the process of merging and testing that everything is working as expected. A release will follow in the next days. Thank you, for you penitence.

Best regards, 
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello!

We now have made a new release which addresses this issue! You can find the updated version in [our releases](https://github.com/wirecard/prestashop-ee/releases/tag/2.3.0).

Best regards,
Wirecard Shop Systems Team
