### ISSUE TITLE
"Test Configuration" doesn't work

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#213]
**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1.28
Module Version: 2.2.1

### Issue

**Problem description:**

Button "Test Configuration" isn't working anymore

**Comment by pretzelhands** [comment]
Hi,

we will fix this is as soon as possible and inform you once the new release is available. Thank you for your feedback.

Best regards,
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello @fuchsbart,

we just tested the "Test Configuration" button in a local installation of PrestaShop 1.7.5.1 and it seems to work as intended. Could you please give us a more detailed description of the steps you took prior to pressing the button?

Thanks a lot,
Wirecard Shop Systems Team

**Comment by fuchsbart** [comment]
We just re-installed the Module v2.2.1 with the pre-filled test data, the button doesn't work.
It's a PS Installation in German, there is also a ContextErrorException in debug mode:

Warning: Declaration of WirecardEE\Prestashop\Helper\TranslationHelper::l($key, $specific = false) should be compatible with AdminControllerCore::l($string, $class = NULL, $addslashes = false, $htmlentities = true)

/controllers/admin/WirecardAjax.php (line 52)

**Comment by pretzelhands** [comment]
Thanks for the information! It seems that the issue only appears when the backend is set to German language. We will take a look at it as soon as possible and notify you when it is solved and a new release has been published.

Best regards,
Wirecard Shop Systems Team

**Comment by pretzelhands** [comment]
Hello!

We now have made a new release which addresses this issue! You can find the updated version in [our releases](https://github.com/wirecard/prestashop-ee/releases/tag/2.3.0).

Best regards,
Wirecard Shop Systems Team
