### ISSUE TITLE
Preference "Challenge Indicator" (Credit Card) not mentioned in Documentation

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#214]
### Versions

**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1.28
Module Version: 2.2.1

### Issue

**Problem description:**

There is a setting called "Challenge Indicator" for credit card payments, but neither the documentation nor the name describe what that means.

**Comment by pretzelhands** [comment]
Hi,

the challenge indicator field is part of an update for the new 3DSecure guidelines coming into effect on September 14, 2019. The meaning and use of this field is explained [in our official documentation center](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2).

We are also currently working on updating our GitHub wiki so it explains the meaning of the field as well.

Best regards,
Wirecard Shop Systems Team
