### ISSUE TITLE
At least one parameter has to be provided: token ID, parent transaction ID

### ISSUE THREAD

**Issue by mschiele** [wirecard/prestashop-ee#224]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/prestashop-ee/wiki/Installation#requirements).
- [X] I am using a [supported version of PrestaShop](https://github.com/wirecard/prestashop-ee/wiki#download-prestashop-shop-module).

### Versions

**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1.3.2

### Issue

**Problem description:**
I'm trying to execute a test purchase with credit card payment method. After filling out the test credit card credentials and confirming my order, I receive the following error "At least one parameter has to be provided: token ID, parent transaction ID". The order successfully arrives in my backend and e-mails get send. But as a customer I should see the order confirmation page, not a red alert box with an error message. There is no error in the prestashop error logs.

A similiar issue occurs when choosing SEPA direct debit...

**Steps to reproduce:**
- add item to cart
- proceed to checkout
- fill out user name and email
- fill out address 
- choose shipping method
- choose payment method and enter test credit card credentials
- the following error occurs
![Bildschirmfoto 2019-09-30 um 22 56 45](https://user-images.githubusercontent.com/6450460/65917756-6a74ee80-e3d8-11e9-8dc7-1552460e5b7e.png)

**Comment by tomazpu** [comment]
Hi, 

we tested the described flow and where not able to reproduce the issue.

As PrestaShop has cache is it possible that you clear you cache and try again ( Advanced Parameters / Performance and clear cache button on the top right). If after this the problem is not resolved maybe you can provide us with more information as logs, server setup for this please contact are support. In case it resolves your problem please give us an update.

Best regards,
Wirecard Shop Systems Team

**Comment by mschiele** [comment]
Hi,

clearing the cache as described above does not resolve the issue. I also did remove cache folder under /var/cache/[env].

I do not get an error in the logs. I get an informative entry that says "Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart".

_FYI: SEPA-Direct Debit is working fine now - the problem was a wrong IBAN which is documented under https://github.com/wirecard/prestashop-ee/wiki/Testing. A colleague of yours provided me a working IBAN. Please update docs with a working IBAN._

**Comment by tomazpu** [comment]
Hi,
thank you for checking.
"Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart". is from PrestaShop and is just informative when the controller gets loaded, you can find it in the core of PrestaShop. 

Is it possible for you to contact are support and share access to your shop so we can analyze the problem?

Sorry for wrong testing credentials in are wiki we will update it as soon as possible.

Best regards,
Wirecard Shop Systems Team

**Comment by mschiele** [comment]
Hi,

there is no error in the log. I debugged my backend...
The exception that gets thrown in your code is the MandatoryFieldMissingException in class CreditCardTransaction.php.
$this->paRes, $this->tokenId and $this->parentTransactionId is all NULL!
I am not sure which of those three parameters at least has to be set. Where does the tokenId come from? The client? I debugged the client's javascript as well. The function which sets tokenId never gets executed. Not sure if this is necessary cause I don't know the wirecard processes.

Yeah it's possible to share access - I already talked to the support today. Please get in touch with Martin Lehmann, should be a colleague of yours. He already knows about the issues.

**Comment by mschiele** [comment]
Any updates?

**Comment by ozada** [comment]
Hi @mschiele,

Our support contacted you today with the solution (it looks your configuration was wrong). Please check your emails for more details. If you have any other questions please open new issue.

Best regards,
Wirecard Shop Systems Team
