### ISSUE TITLE
Test Order gets no Status Update

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#232]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/prestashop-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of PrestaShop](https://github.com/wirecard/prestashop-ee/wiki#download-prestashop-shop-module).

### Problem

Our test orders remain on the same initial order status: "Wirecard payment started".
We test the payment methods credit card, SEPA direct debit and Sofort. The test payments work and are displayed in the backend on the order page, but without transaction ID. The list of Wirecard transactions also remains empty.

**Comment by rinnhofer** [comment]
Hello @fuchsbart ,

it is possible that you are not receiving notifications from our system. Could you please verify if you get notifications from our Payment Gateway by checking your logs as described here:
https://github.com/wirecard/prestashop-ee/wiki/Debugging-and-Error-Logs

If you do not get any notifications it is possible that your firewall is blocking these notifications and you have to update your firewall rules.

Kind regards,
Wirecard Shop Systems Team

**Comment by tomazpu** [comment]
Hello @fuchsbart, 

Without the log file, it's almost impossible to say what is going wrong. We try a test run and where not able to reproduce your issue. I suggest that you contact our support:
Phone: +61 1300 599 991
Email: shop-systems-support@wirecard.com

As they will happily help you to fix the issue.

Best regards, 
Tomaz

**Comment by fuchsbart** [comment]
I can break this problem down to the example that a test order with SEPA Direct Debit never switches to "Payment received".

**Comment by tomazpu** [comment]
Hello @fuchsbart,

for SEPA Direct Debit, this is normal behavior. On the test instance, the notification which are to confirmation of order doesn't get sent from the engine. On the production, this will never happen.

If that resolves your issue please close the ticket. If not contact support.

Best regards,
Tomaz
