### ISSUE TITLE
Credit card 3D-secure dialogue: Cancel or wrong password creates an order and sets error status twice

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#235]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/prestashop-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of PrestaShop](https://github.com/wirecard/prestashop-ee/wiki#download-prestashop-shop-module).

### Versions

**PrestaShop version:** 1.7.5.1
**PHP version:** 7.1

### Issue

If the 3d-secure dialog is aborted or aborted by too many wrong password attempts, the redirection goes to the first page of the checkout process with the following error message:

*"3d-acquirer:The cardholder not only cancelled but even denied the payment process. No liability shift is granted and payment should not be processed as customer expressed his explicit denial.
The Parent Transaction Id was not successful, the operation is not possible. Please do not try again."*

The shopping cart and the checkout data are still there, the customer has to go through the checkout again until the payment step.

Although the payment failed, an order is created in the backend. This sends the customer an order confirmation.

After the status "Wirecard Payment started" the status "Payment error" is set, but twice! As a result, the corresponding e-mail is also sent twice to the customer.

For the created order, there is also a payment shown in the backend. The payment does not have an transaction ID.

**Comment by tomazpu** [comment]
Hello @fuchsbart,

an order is created when the consumer clicks on submit. Then if he will enter wrong credentials in the 3d-secure dialog, the plugin will receive from the API an error. What you describe is the wanted workflow(except that the status is set twice, which results in a double send error email).

We will fix the issue with the status and email as soon as possible.
Thank you for your feedback.

Best regards,
Tomaz

**Comment by tomazpu** [comment]
Hello @fuchsbart, 

PrestaShop itself cannot recreate the order. As you already described the plugin is receiving an error from the engine so it sets the order to error and then recreates the order with the same cart items which are a feature of our plugin so that the consumer then only needs to go to the payment process again. Unfortunately, the only possible way is to redirect him to checkout, we are not able to set the "Page" to be just the payment selection.

You are right that the two error emails are confusing and will be fixed, I think it's clear to the customer why he is back at the checkout page as in the red box he will have the error message displayed of what went wrong.

Best regards,
Tomaz

**Comment by fuchsbart** [comment]
Hello @tomazpu ,
>I think it's clear to the customer why he is back at the checkout page as in the red box he will have the error message displayed of what went wrong.

on this point, I have to disagree. It is not apparent to the customer during checkout that his order has just been recreated. He only gets the error warning that his payment did not work.
The fact that the shop system records the order with incorrect payment as a "corpse" has a purely technical background. The best user experience would be if the payment for the same order could be repeated until it works.
With the Wirecard module's behavior, its order is displayed in the checkout as if it had not been completed. Nevertheless, he receives an order confirmation e-mail, which must be designed for complete or successful orders (congratulations, your order has been accepted, etc.). This results in a user experience that is extremely confusing - which falls back on the shop and its reputation.  Other payment providers such as Stripe are able to validate the payment before Prestashop creates the order!

**Comment by cpfoser** [comment]
@fuchsbart 
thanks for your input, we will evaluate how other payment providers resolve this issue technically. If they do not break the shop-systems' behaviour we will put feature on our roadmap. 

Best regards, 
Wirecard Shop Systems Team

**Comment by fuchsbart** [comment]
Hello @cpfoser,
did you evaluate any solutions? Is there any plan to modify the module?

Thanks

**Comment by cpfoser** [comment]
Hi  @fuchsbart 

there are plans to modify the module but not any known timelines yet. 
As of now the solution we provide will remain.

Thus, I will close this issue. 

Best, 
Caroline
