### ISSUE TITLE
Credit Card Number – Validation fails if Number is pasted

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#244]
The pasting of the credit card number results in an error message that no number has been entered.

![Bildschirmfoto 2019-11-15 um 15 02 13](https://user-images.githubusercontent.com/30295473/68948910-3ce1da00-07b9-11ea-9a64-5358d6328ce5.png)

**Comment by mke-wd** [comment]
Hello @fuchsbart ! 

Thanks for the hint! We need your help to be able to reproduce and fix the issue. Can you please answer me the following questions:
- Which OS are you using?
- Which browser and version are you using? 
- Has there been any autofill plugin or similiar involved?

Thanks for you help and BR
Moritz
