### ISSUE TITLE
Translated Error Messages

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#345]
We are waiting since October 2019 for translated error messages.

posted by @cpfoser in https://github.com/wirecard/prestashop-ee/issues/233#issuecomment-589563409_

Any updates?

**Comment by cpfoser** [comment]
@fuchsbart 

As far as I know there is now a solution design ready which will be implemented. (Unfortunately I have not any timeline yet).

Once this is implemented we will implement this feature based on our given priorities. 

Best regards,
Wirecard Shop-Systems Team
